Status bar tests
software-mansion/vscode-cairo pull request #24
Opened 2024-12-10 13:27 UTC by Draggu

2024-12-10 14:04 UTC, piotmag769 approved these changes
Looks good for my non-ts-js eye

2024-12-10 14:44 UTC, integraledelebesgue approved these changes
Looks fine (as far as I'm able to tell about TS and plugin :v)

2024-12-11 07:28 UTC, mkaput requested changes

2024-12-11 07:28 UTC, mkaput commented on test-support/scarb.ts
> +import commandExists = require("command-exists");
why are you not using es6 imports?

2024-12-11 07:28 UTC, mkaput commented on test-support/scarb.ts
> +    .catch(() => false);
1. camelCase
2. this sounds like something we might want to cache as a global variable

```suggestion
export const scarbAvailable = commandExistsSync("scarb");
```

2024-12-11 07:28 UTC, mkaput commented on ui-test-resources/empty/Scarb.lock
can this directory be put inside `ui-tests`? we're proliferating top-level directories too much imo

also I think it should be called `fixtures`

2024-12-11 07:28 UTC, mkaput commented on test-support/scarb.ts
this directory is not using typescript so let's skip it also for this file

2024-12-11 07:28 UTC, mkaput commented on ui-test/statusBar.ts
> +describe("Status bar test", function () {
```suggestion
describe("status bar", function () {
```

the whole idea is that all `describe` + `it` calls in the stack form a proper English sentence describing what behaviour is tested

2024-12-11 07:28 UTC, mkaput commented on ui-test/statusBar.ts
> +  it("checks if status bar is displaying correct message", async function () {
```suggestion
  it("displays Cairo toolchain version", async function () {
```

2024-12-11 07:28 UTC, mkaput commented on ui-test/statusBar.ts
> +    await new Promise((done) => setTimeout(done, 2000));
2 seconds is a dramatic test execution time increase. we should wait for the statusbar to disappear with such deadline, not always wait so much

2024-12-12 13:22 UTC, merged