Status bar tests
software-mansion/vscode-cairo pull request #30
Opened 2024-12-12 13:43 UTC by Draggu

**Stack**:
- #29
- #22

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2024-12-12 14:27 UTC, mkaput requested changes

2024-12-12 14:27 UTC, mkaput commented on test-support/scarb.ts
> +    .catch(() => false));
```suggestion
import { sync as commandExistsSync } from "command-exists";

export const isScarbAvailable = commandExistsSync("scarb");
```

2024-12-13 13:22 UTC, mkaput requested changes

2024-12-13 13:22 UTC, mkaput commented on test-support/scarb.ts
> +export const isScarbAvailable = () => commandExists("scarb");
```suggestion
export const isScarbAvailable = commandExists("scarb");
```

discussed offline 😆

2024-12-13 13:24 UTC, mkaput approved these changes

2024-12-13 15:16 UTC, piotmag769 approved these changes

2024-12-16 09:17 UTC, Arcticae commented on test-support/scarb.ts
> +export const isScarbAvailable = commandExists("scarb");
```suggestion
export const scarbIsAvailable = commandExists("scarb");
```

2024-12-16 10:24 UTC, mkaput commented on test-support/scarb.ts
> +export const isScarbAvailable = commandExists("scarb");
tbh looks bad to my eyes

2024-12-16 12:44 UTC, merged